language: r
cache: packages
pandoc_version: 2.10.1

addons:
  apt:
    packages:
    - cargo
    - libpoppler-cpp-dev
    - libmagick++-dev
    - asymptote
    - libgit2-dev
    - libharfbuzz-dev
    - libfribidi-dev
    - libgit2-dev
    - libglu1-mesa-dev

services:
  - xvfb

script:
  - xvfb-run -a make gitbook
  - ./_deploy.sh
